### ISSUE TITLE
Migrate from an earlier version of Bonita BPM - Remove info

### ISSUE THREAD

**Issue by goenkale** [bonitasoft/bonita-doc#139]
[Link](http://documentation.bonitasoft.com/bonitabpm/?page=migrate-from-an-earlier-version-of-bonita-bpm#toc4)
In "Migrate your platform" secction, step 6 says: 
"Stop the application server and database server."

Remove the part " and database server.".

**Comment by julienmege** [comment]
Hello,
we would like to avoid to use a new channel to track issues.
Can you make a pull request for this? 
It will be the fastest way to integrate your feedback, else create a support ticket.

**Comment by lcustodio** [comment]
Issue solved, ready to close.
